### ISSUE TITLE
Layout components

### ISSUE THREAD

**Issue by bajki** [Patrick-Spiegel/vue-grapesjs#1]
Can you add v-container , v-layout and v-flex so it would work with vuetify?

Thanks,
Ivan

**Comment by Patrick-Spiegel** [comment]
Hello,

this is intended as an example of how you can add vue to grapesjs. You should be able to follow the example [here](https://github.com/Patrick-Spiegel/vue-grapesjs/tree/master/src/components/grapes-components/v-btn) and add layout containers yourself.

**Comment by bajki** [comment]
I can't manage to render v-layout inside v-container on this example..
It creates div and inside renders v-container, and when you drop element inside it should push it to v-container but it does not.
